# Generated by Django 5.1.2 on 2025-01-16 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dealers_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
                ('id_proof_number', models.BigIntegerField()),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='product_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='complaint_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('replay', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('DEALEARS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.dealers_table')),
            ],
        ),
        migrations.CreateModel(
            name='feedback_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('rating', models.IntegerField()),
                ('date', models.DateField()),
                ('DEALEARS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.dealers_table')),
            ],
        ),
        migrations.CreateModel(
            name='job_request_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('DEALEARS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.dealers_table')),
            ],
        ),
        migrations.AddField(
            model_name='dealers_table',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table'),
        ),
        migrations.CreateModel(
            name='administrative_staff_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('id_proof_number', models.BigIntegerField()),
                ('image', models.FileField(upload_to='')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='purchase_request_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('DEALEARS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.dealers_table')),
            ],
        ),
        migrations.CreateModel(
            name='purchase_request_more_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product_table')),
                ('PURCHASE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.purchase_request_table')),
            ],
        ),
        migrations.CreateModel(
            name='workers_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('skills', models.TextField()),
                ('availability', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
                ('id_proof_number', models.BigIntegerField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='allocate_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('allocation_date', models.DateField()),
                ('JOB_REQUEST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.job_request_table')),
                ('WORKER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.workers_table')),
            ],
        ),
    ]
