# Generated by Django 5.1.2 on 2025-01-29 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_request_table',
            name='amount',
        ),
    ]
