# Generated by Django 5.1.2 on 2025-02-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_job_request_table_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocate_work',
            name='status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
