# Generated by Django 5.1.2 on 2025-02-17 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_allocate_work_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(max_length=100)),
                ('PURCHASE_REQUEST_TABLE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.purchase_request_table')),
            ],
        ),
    ]
