# Generated by Django 5.1.2 on 2025-02-18 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_table',
            name='PRODUCT',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='myapp.product_table'),
            preserve_default=False,
        ),
    ]
